name: Create release branch
description: Create a release branch and PR into master

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.14

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run script
      shell: bash
      run: python ${{ github.action_path }}/create_release_branches.py
