name: PR Branch Warning

on:
  pull_request:
    branches: [ "main", "master" ]
    types: [ opened ]

permissions:
  pull-requests: write

jobs:
  warn:
    runs-on: ubuntu-latest
    steps:
      - name: Add warning comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const baseBranch = context.payload.pull_request.base.ref;

            const commentBody = `@${prAuthor} you are trying to merge into \`${baseBranch}\`!\n` +
              "Please ensure this is intentional.\n" +
              `Feature branches should normally be merged into \`develop\`.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody,
            });
